AyasofyaCamiiurlsi = 'https://www.kutsalkitap.org/ayasofya/?gclid=EAIaIQobChMI7JL43OjS7AIVw_ZRCh1_iQSREAAYASAAEgIAR_D_BwE'
SultanAhmetCamiiurlsi = 'https://www.garenta.com.tr/blog/bir-istanbul-guzellemesi-sultan-ahmet-camii/'
LaraDudenWaterfallurlsi = 'https://www.antalyagezirehberi.net/asagi-duden-selalesi.html'
HadrianCastleGateurlsi = 'https://www.antalyagezirehberi.net/hadrianus-kapisi.html'
IzmirClockTowerurlsi = 'https://www.kulturportali.gov.tr/turkiye/izmir/gezilecekyer/saat-kulesi404803'
IzmirHistoricalElevatorBuildingurlsi = 'https://gezilmesigerekenyerler.com/izmir/izmir-tarihi-asansor-nerede-tarihi-bilgiler.html'
